name: Gas Snapshot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gas-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run gas snapshot tests
        run: forge test --match-contract Gas_Snapshots --gas-report
