name: gas-snapshot

on:
  push:
    branches: [ main, feat/**, ci/**, test/** ]
    paths:
      - "src/**"
      - "test/Gas_Snapshots.t.sol"
      - ".github/workflows/gas-snapshot.yml"
      - "foundry.toml"
  pull_request:
    branches: [ main ]
    paths:
      - "src/**"
      - "test/Gas_Snapshots.t.sol"
      - ".github/workflows/gas-snapshot.yml"
      - "foundry.toml"

jobs:
  gas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Build
        run: forge build

      - name: Run gas report
        run: forge test --match-contract Gas_Snapshots --gas-report -vv

      - name: Upload gas report artifact
        uses: actions/upload-artifact@v4
        with:
          name: gas-report
          path: |
            ./out
            ./cache
