name: gas-tests

on:
  push:
    branches: [ main, feat/**, ci/**, test/** ]
    paths:
      - "src/**"
      - "test/**.t.sol"
      - ".github/workflows/ci.yml"
      - "foundry.toml"
  pull_request:
    branches: [ main ]
    paths:
      - "src/**"
      - "test/**.t.sol"
      - ".github/workflows/ci.yml"
      - "foundry.toml"

jobs:
  gas-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable
      - run: forge build
      - name: Run gas snapshot tests
        run: forge test --gas-report -vv
