name: vault-tests

on:
  push:
    branches: [ main, feat/**, ci/**, test/** ]
    paths:
      - "src/**"
      - "test/VaultWrBTC_ERC20_Unit.t.sol"
      - ".github/workflows/vault-tests.yml"
      - "foundry.toml"
  pull_request:
    branches: [ main ]
    paths:
      - "src/**"
      - "test/VaultWrBTC_ERC20_Unit.t.sol"
      - ".github/workflows/vault-tests.yml"
      - "foundry.toml"

permissions:
  contents: read

jobs:
  vault-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Foundry (stable)
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Build
        run: forge build

      - name: Run Vault ERC20 unit tests
        run: forge test --match-path test/VaultWrBTC_ERC20_Unit.t.sol -vv
